"""Agregar id

Revision ID: 24e065fc4544
Revises: c339f8bf2b26
Create Date: 2025-05-25 13:22:18.833493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24e065fc4544'
down_revision = 'c339f8bf2b26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proyecto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario_id_p', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'usuario', ['usuario_id_p'], ['id_usuario'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proyecto', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('usuario_id_p')

    # ### end Alembic commands ###
