"""Actualizar tabla

Revision ID: 815103450e29
Revises: 8b1044fc9ef8
Create Date: 2025-05-25 13:11:46.115788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '815103450e29'
down_revision = '8b1044fc9ef8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proyecto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'categoria', ['categoria_id'], ['id_categoria'])

    with op.batch_alter_table('tarea', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('FK__tarea__catalogo___66603565'), type_='foreignkey')
        batch_op.drop_column('catalogo_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tarea', schema=None) as batch_op:
        batch_op.add_column(sa.Column('catalogo_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('FK__tarea__catalogo___66603565'), 'categoria', ['catalogo_id'], ['id_categoria'])

    with op.batch_alter_table('proyecto', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('categoria_id')

    # ### end Alembic commands ###
