"""Agrega tabla Proyecto

Revision ID: 8b1044fc9ef8
Revises: 
Create Date: 2025-05-25 09:40:42.449809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b1044fc9ef8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tarea', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proyecto_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'proyecto', ['proyecto_id'], ['id_proyecto'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tarea', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('proyecto_id')

    # ### end Alembic commands ###
