"""Agregar descripcion al pro

Revision ID: c339f8bf2b26
Revises: 815103450e29
Create Date: 2025-05-25 13:19:51.415535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c339f8bf2b26'
down_revision = '815103450e29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proyecto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripcion_proyecto', sa.String(length=150), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proyecto', schema=None) as batch_op:
        batch_op.drop_column('descripcion_proyecto')

    # ### end Alembic commands ###
